name: Build oneDNN with ACL on Arm64
permissions:
  contents: write
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 3 * * *" # every day at 3 AM UTC

jobs:
  build-arm64:
    name: Build on ubuntu-24.04-arm
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git cmake ninja-build build-essential \
            python3 python3-pip scons \
            opencl-headers ocl-icd-opencl-dev

      - name: Build Arm Compute Library (NEON + OpenCL)
        run: |
          git clone --depth=1 https://github.com/ARM-software/ComputeLibrary.git
          cd ComputeLibrary
          scons arch=armv8a \
                build=native \
                opencl=1 \
                neon=1 \
                embed_kernels=1 \
                Werror=0 -j$(nproc)
          ls build
          cd ..

      - name: Build oneDNN with ACL backend
        run: |
          git clone --depth=1 https://github.com/oneapi-src/oneDNN.git
          cd oneDNN
          mkdir build && cd build
          cmake .. \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/opt/onednn-acl-install \
            -DDNNL_CPU_RUNTIME=OMP \
            -DACL_INCLUDE_DIR=../../ComputeLibrary/include/ \
            -DACL_EXTRA_INCLUDE_DIR=../../ComputeLibrary/ \
            -DACL_LIBRARY=../../ComputeLibrary/build/libarm_compute-static.a \
            -DDNNL_GPU_RUNTIME=OCL \
            -DDNNL_AARCH64_USE_ACL=ON \
            -DACL_GRAPH_LIBRARY="../../ComputeLibrary/build/libarm_compute_graph-static.a" \
            -DDNNL_ENABLE_WORKLOAD=INFERENCE \
            -DONEDNN_LIBRARY_TYPE=STATIC
          ninja -j$(nproc)
          sudo ninja install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: onednn-acl-arm64
          path: /opt/onednn-acl-install
